on: [push]

jobs:
  build-and-test-in-bash:
    strategy:
      # Continue build even if some platforms fail.
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            arch: arm64
          - os: ubuntu-latest
            arch: x64
          - os: windows-latest
            arch: x64
    runs-on: ${{ matrix.os }}
    name: Build and test in Bash
    steps:
      - name: Ensure same LF line endings on all platforms
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - uses: radekm/setup-c3@v2
        with:
          # Tests need 0.7.9 which is not yet out.
          version: v0.7.8
      - shell: bash
        run: |
          time ./test.sh
